#!/bin/bash

PROXY_PATH=./tcproxy
PROXY_CONF=./tcproxy.conf
PROXY_LOG_DIR=.

# Get the proxy executable name 
PROXY_NAME=`basename $PROXY_PATH`

# Compose logfile name based on program name without extension
LOG_FILE=$PROXY_LOG_DIR/${PROXY_NAME%.*}.log

# Start proxy process
echo Starting $PROXY_PATH
echo Check $LOG_FILE for start-up errors

nohup $PROXY_PATH $PROXY_CONF >> $LOG_FILE 2>&1 &


